front_matter = {
    "qid": 389,
    "title": "Find the Difference",
    "titleSlug": "find-the-difference",
    "difficulty": "Easy",
    "tags": ["Hash Table", "String", "Bit Manipulation", "Sorting"],
}
# ====================== DO NOT EDIT ABOVE THIS LINE ======================
class Solution:
    """You are given two strings `s` and `t`.

    String `t` is generated by random shuffling string `s` and then add one more letter at a random position.

    Return the letter that was added to `t`.



    **Example 1:**

    ```
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    ```
    **Example 2:**

    ```
    Input: s = "", t = "y"
    Output: "y"
    ```


    **Constraints:**

    * `0 <= s.length <= 1000`
    * `t.length == s.length + 1`
    * `s` and `t` consist of lowercase English letters.
    """

    def findTheDifference(self, s: str, t: str) -> str:
        pass

    # If you have multiple solutions, add them all here as methods of the same class.
